### ISSUE TITLE
2018-04-09 9.00AM-12.00AM | 新世纪妇女儿童医院 | iOS 端需求测试 | Issus 反馈即可

### ISSUE THREAD

**Issue by medz** [zhiyicx/test-group-worker-forum#103]
2018-04-09 13.30PM-6.00PM | 新世纪妇女儿童医院 | iOS 端需求测试 | Issus 反馈即可

## 基本信息

- 测试项目：新世纪妇女儿童医院
    - iOS 端
- 测试版本：v1.0.0
- 对接人：胡爽
- 测试时间：2018-04-09 13.30PM-6.00PM
- 需求人数：2 人

## 仓库

| 仓库名称 | 仓库地址 |
|:----:|----|
| iOS 仓库 | https://github.com/zhiyicx/xinshiji-iOS |

## 目的

- [x] 交付需求测试

## 测试内容

- iOS 端需求用例测试
- iOS 端 Bug 探索

## 模板

`zhiyicx/xinshiji-iOS#100`

> 将上述的 100 替换为对应的 Issue 编号

**Comment by LMTcancan** [comment]
## Android
### 已修复
- 【消息-群聊】移除群成员时，点击移除自己，出现“操作中”指示器，且一直存在 zhiyicx/xinshiji-android#17
- 【消息-聊天室】查看聊天信息时，点击医生头像无法进入医生主页 zhiyicx/xinshiji-android#13
- 【消息-群聊】新进群成员，能收到进群之前的消息 zhiyicx/xinshiji-android#8
- 【消息--群聊】添加邀请其他用户进入群聊后，返回群信息页面出现"+"或“—”显示最后添加的用户头像 zhiyicx/xinshiji-android#5


## iOS
### 新增
- 【消息】消息列表中未显示每个聊天室最后的消息 zhiyicx/xinshiji-iOS#1
- 【消息-群聊】医生无法创建群聊 zhiyicx/xinshiji-iOS#5
- 【消息-聊天室】进入聊天室会显示所有语音自动播放效果 zhiyicx/xinshiji-iOS#8
- 【消息-群聊】查看聊天室信息无内容 zhiyicx/xinshiji-iOS#9
- 【消息-群聊-聊天信息】医生修改群名称，点击完成按钮后，APP崩溃 zhiyicx/xinshiji-iOS#11
- 【消息-群聊】点击退出群聊并确认后无反应 zhiyicx/xinshiji-iOS#12
- 【消息-联系人】医生账号点击非医生账号进入聊天室页面时，一部分用户名称不正确 zhiyicx/xinshiji-iOS#14
- 【消息-群聊】添加群聊成员时，显示了所有用户 zhiyicx/xinshiji-iOS#16
- 【消息】医生给用户发消息，在消息列表中未显示 zhiyicx/xinshiji-iOS#18
- 【消息列表】断开网络后从聊天室页面返回消息列表，会出现多余的内容 zhiyicx/xinshiji-iOS#22
- 【消息-群聊】他人创建的新群聊，在消息列表名称显示错误，聊天室显示也有误 zhiyicx/xinshiji-iOS#23
- 【消息】收到的消息缺少小红点 zhiyicx/xinshiji-iOS#26
- 【消息-聊天室】他人发送图片或位置时，缺少他人的昵称 zhiyicx/xinshiji-iOS#27

**Comment by maanrry** [comment]
## ios
### 新增：
- 【消息-群聊】有创建群信息时，在群聊天室没有显示 zhiyicx/xinshiji-iOS#2
- 【消息-群聊】已经有头像的在聊天室头像显示还是默认头像 zhiyicx/xinshiji-iOS#3
- 【消息-医生-在线咨询】非会员账号点击“在线咨询”进入的页面不对  zhiyicx/xinshiji-iOS#4
- 【消息-医生-在线咨询】会员账号点击“在线咨询”不能进入相应的页面 zhiyicx/xinshiji-iOS#6
- 【消息-聊天室】聊天室不显示emoji zhiyicx/xinshiji-iOS#7
- 【消息-聊天室】进入聊天信息页面点击头像进入其个人主页点击“关注”app崩溃 zhiyicx/xinshiji-iOS#10
- 【消息】在列表上滑动无法删除聊天室 zhiyicx/xinshiji-iOS#13
- 【消息-聊天室】发送图片在聊天室显示不对 zhiyicx/xinshiji-iOS#15
- 【消息】从聊天信息进入个人主页后返回消息列表会新增一个空白的聊天室区域 zhiyicx/xinshiji-iOS#17
- 【消息-聊天室】当消息内容为纯文字并且很长时，无法上滑查看全部内容 zhiyicx/xinshiji-iOS#19
- 【消息-联系人】键盘弹出之后把已选中的用户头像遮住 zhiyicx/xinshiji-iOS#20
- 【消息-聊天】普通成员仍然有群聊名称入口 zhiyicx/xinshiji-iOS#21
- 【消息-群聊】普通成员仍然可以邀请其他用户进入群聊 zhiyicx/xinshiji-iOS#24
- 【消息-聊天室】输入要发送的内容后断网点击“发送”没有反应 zhiyicx/xinshiji-iOS#25
