### ISSUE TITLE
2018-04-09 13.30PM-6.00PM | 轰米社区 | iOS 端交付测试 | Issus 反馈即可

### ISSUE THREAD

**Issue by medz** [zhiyicx/test-group-worker-forum#104]
2018-04-09 13.30PM-6.00PM | 轰米社区 | iOS 端交付测试 | Issus 反馈即可

## 基本信息

- 测试项目：轰米社区
    - iOS 端
- 测试版本：v1.0.5
- 对接人：李育东
- 测试时间：2018-04-09 13.30PM-6.00PM
- 需求人数：2 人

## 仓库

| 仓库名称 | 仓库地址 |
|:----:|----|
| iOS 仓库 | https://github.com/zhiyicx/t4-homie-ios |

## 目的

- [x] 交付客户测试

## 测试内容

- iOS 端新 Bug 探索
- 测试仓库标记 `Fixed` 标签的 Issue

## 模板

`zhiyicx/t4-homie-ios#100`

> 将上述的 100 替换为对应的 Issue 编号

**Comment by LMTcancan** [comment]
## Android
### 已修复
- 【homie-消息-聊天室】断网之后发送消息10多分钟都没有感叹号 zhiyicx/t4-homie-android#196
- 【HOMIE-活动-活动详情】活动成员头像显示为缺省图 zhiyicx/t4-homie-android#194
- 【我的-生涯-日迹】当天发布多个新鲜事时，上下滑动列表，日期位置不断变化 zhiyicx/t4-homie-android#192
- 【我的-生涯-日迹】多处与设计图不符 zhiyicx/t4-homie-android#191
- 【他人个人主页】进入他人个人主页后断开网络，下拉加载日迹没有检查网络提示 zhiyicx/t4-homie-android#190
- 【新鲜事】转发的新鲜事带有图片和多行文字时，图片位置没有在正中 zhiyicx/t4-homie-android#198
- 【HOMIE-消息-互动】互动列表全部显示为默认头像 zhiyicx/t4-homie-android#197
- 【HOMIE-活动-活动详情】断网情况下，点击感兴趣，活动成员，活动评论提示语错误 zhiyicx/t4-homie-android#195
- 【HOMIE-活动-活动详情-活动评论】回复他人评论后，他人用户名不应该显示为灰色 zhiyicx/t4-homie-android#193
- 【homie-消息】进入消息页面后断网下拉刷新没有检查网络提示 zhiyicx/t4-homie-android#189

### 重新打开
- 【HOMIE-活动-活动详情】断网情况下，点击感兴趣，活动成员，活动评论提示语错误 zhiyicx/t4-homie-android#195

### 新增
- 【HOMIE-消息-互动】互动列表全部显示为默认头像 zhiyicx/t4-homie-android#197
- 【新鲜事】转发的新鲜事带有图片和多行文字时，图片位置没有在正中 zhiyicx/t4-homie-android#198
- 【HOMIE-消息-陌生人】在消息页面多次点击进入群聊后退出，进入陌生人消息会出现其他聊天信息 zhiyicx/t4-homie-android#199
- 【HOMIE-消息-互动】互动消息有多处错误 zhiyicx/t4-homie-android#200
- 【HOMIE-发现-活动-活动评论】输入评论内容后断开网络，点击评论，提示错误 zhiyicx/t4-homie-android#201
- 【新鲜事-话题-搜索】搜索结果展示错误 zhiyicx/t4-homie-android#202
- 【HOMIE-消息】新注册的账号，没有关注和粉丝，收到陌生人消息点击查看后，APP崩溃 zhiyicx/t4-homie-android#203
- 【新鲜事-话题-话题详情】有两处与设计图不符 zhiyicx/t4-homie-android#204
- 【HOMIE-发现】当可能认识的人没有时，占位文字显示错误 zhiyicx/t4-homie-android#205
- 【我的-更多-相册】选择多张图片上传时，只上传成功一张图片 zhiyicx/t4-homie-android#206
- 【我的-更多-相册】编辑相册，缺少删除按钮，点击删除多张图片，APP崩溃 zhiyicx/t4-homie-android#207
- 【我的-更多-相册】当相册没有图片时，上传图片，缺省图未消失 zhiyicx/t4-homie-android#208


## iOS
### 已修复
- 【HOMIE-活动】发布活动时，活动详情输入emoji后保存，返回显示位置不正确 zhiyicx/t4-homie-ios#227
- 【HOMIE-活动】活动列表无法下拉加载更多活动 zhiyicx/t4-homie-ios#226
- 【HOMIE-活动】发起活动输入活动详情时，同时添加图片和视频，提示框与整体风格不一致 zhiyicx/t4-homie-ios#225
- 【HOMIE-发现-活动】发起活动时，未保存活动地点就返回，返回后仍显示了之前选择的地点 zhiyicx/t4-homie-ios#219
- 【HOMIE-发现-活动】开启了定位权限，活动仍显示未定位 zhiyicx/t4-homie-ios#209
- 【新鲜事-发布】点击发布视频后未进入视频录制页面 zhiyicx/t4-homie-ios#206
- 【HOMIE-发现-活动-发布活动】活动详情同时输入emoji和文字时，返回发布活动页面，文字是黑色 zhiyicx/t4-homie-ios#188
- 【新鲜事-发布】上传图片，图片被裁剪 zhiyicx/t4-homie-ios#187


### 重新打开
- 【HOMIE-活动】选择标签时会弹出全部标签 zhiyicx/t4-homie-ios#224
- 【全局】断网时发布评论，提示框与整体设计不符 zhiyicx/t4-homie-ios#211
- 【我的-更多-我的活动】活动靠谱指数显示null，活动发起者头像显示为默认 zhiyicx/t4-homie-ios#120

### 新增
- 【新鲜事-发布】第一次发布视频时，提示框与整体效果不符 zhiyicx/t4-homie-ios#228
- 【新鲜事】新鲜事带有话题和@时，转发后话题颜色没有变蓝，@显示错误 zhiyicx/t4-homie-ios#230
- 【我的-生涯-日迹】转发的新鲜事展示有多处错误 zhiyicx/t4-homie-ios#231
- 【HOMIE-发现-活动-活动评论】点击头像进入的是T4的个人主页 zhiyicx/t4-homie-ios#233
- 【HOMIE-消息-互动】活动评论内容过多时，未做适配，会发生遮挡 zhiyicx/t4-homie-ios#235
- 【他人个人主页-生涯-日迹】查看他人日迹时，滑动到固定位置界面卡死（特殊账号） zhiyicx/t4-homie-ios#238
- 【HOMIE-发现-靠谱榜】靠谱榜排名数字不正确 zhiyicx/t4-homie-ios#240
- 【我的-更多-意见反馈】意见反馈添加图片数量未做限制，与需求不符 zhiyicx/t4-homie-ios#243
- 【权限】用户设置了隐私权限，但没有做限制 zhiyicx/t4-homie-ios#245

**Comment by maanrry** [comment]
## ios
### 已修复：
- 【homie--关注】多次点击“搜索”导致多条数据 zhiyicx/t4-homie-ios#181
- 【homie--消息--联系人】选择用户后上下滑动，背景变成白色 zhiyicx/t4-homie-ios#192
- 【新鲜事】列表上点击“话题”未跳转到改话题详情页 zhiyicx/t4-homie-ios#195
- 【新鲜事】断网后下来刷新提示语被隐藏 zhiyicx/t4-homie-ios#197
- 【我的-资料-学校】不允许访问当前位置时添加学校定位显示错误 zhiyicx/t4-homie-ios#198
- 【homie-消息-聊天室】聊天详情页点击“语音”后向右滑动语音图标一直不消失 zhiyicx/t4-homie-ios#216
- 【homie-发现】仍然有选择好友入口 zhiyicx/t4-homie-ios#222
- 【新鲜事】删除新鲜事和举报他人的新鲜事的弹窗与整体设计风格不一致 zhiyicx/t4-homie-ios#156
### 新增：
- 【登录】当输入的手机号错误时，修改除了最后一位的任意一位或几位并且满足11位时不再出现“获取验证码” zhiyicx/t4-homie-ios#229
- 【homie-消息】先将聊天室删除后有陌生人发送消息后最后一次被删除的聊天室会出现在列表上 zhiyicx/t4-homie-ios#232
- 【新鲜事】当用户昵称过程时未用"...”表示 zhiyicx/t4-homie-ios#234
- 【发布新鲜事】先录制视频然后再拍照上传，将图片删除之后还是视频图标 zhiyicx/t4-homie-ios#236
- 【发布新鲜事】键盘弹出来时预览视频，键盘未隐藏 zhiyicx/t4-homie-ios#237
- 【homie-消息-联系人】没有任何关注的用户时，缺省图与整体的缺省图不一致 zhiyicx/t4-homie-ios#239
- 【缺省图】多个页面缺少缺省图 zhiyicx/t4-homie-ios#241
- 【我的-更多-相册】删除图标与设计不符 zhiyicx/t4-homie-ios#242
- 【新鲜事-新鲜事详情】将评论删除之后再次进入新鲜事详情页评论数并没有减少 zhiyicx/t4-homie-ios#244
- 【我的-生涯-日迹】列表上没有显示评论数和点赞数 zhiyicx/t4-homie-ios#246
