### ISSUE TITLE
2018-04-10 9.00AM-6.00PM | ThinkSNS Plus | App 短视屏 | Issus 反馈即可

### ISSUE THREAD

**Issue by medz** [zhiyicx/test-group-worker-forum#105]
2018-04-10 9.00AM-6.00PM | ThinkSNS Plus | App 短视屏 | Issus 反馈即可

## 基本信息

- 项目名称：ThinkSNS Plus
    - Android 端
    - iOS 端
- 测试版本：1.8.*
- 对接人：贺华军
- 测试时间：2018-04-10 9.00AM-6.00PM
- 需求人数：2 人

## 仓库

| 仓库名称 | 仓库地址 |
|:----:|----|
| Android | https://github.com/zhiyicx/thinksns-plus-android |
| iOS | https://github.com/zhiyicx/thinksns-plus-ios |
| Server | https://github.com/slimkit/thinksns-plus |

## 目的

- [x] 交付需求测试

## 测试内容

- 短视屏需求开发交付测试

## 模板

Android:
```
zhiyicx/thinksns-plus-android#100
```

iOS:
```
zhiyicx/thinksns-plus-ios#100
```

> 将上述的 100 替换为对应的 Issue 编号

**Comment by maanrry** [comment]
## ios
### 新增：
- 【消息-群聊】有创建群信息时，在群聊天室没有显示 zhiyicx/xinshiji-iOS#2
- 【消息-群聊】已经有头像的在聊天室头像显示还是默认头像 zhiyicx/xinshiji-iOS#3
- 【消息-医生-在线咨询】非会员账号点击“在线咨询”进入的页面不对  zhiyicx/xinshiji-iOS#4
- 【消息-医生-在线咨询】会员账号点击“在线咨询”不能进入相应的页面 zhiyicx/xinshiji-iOS#6
- 【消息-聊天室】聊天室不显示emoji zhiyicx/xinshiji-iOS#7
- 【消息-聊天室】进入聊天信息页面点击头像进入其个人主页点击“关注”app崩溃 zhiyicx/xinshiji-iOS#10
- 【消息】在列表上滑动无法删除聊天室 zhiyicx/xinshiji-iOS#13
- 【消息-聊天室】发送图片在聊天室显示不对 zhiyicx/xinshiji-iOS#15
- 【消息】从聊天信息进入个人主页后返回消息列表会新增一个空白的聊天室区域 zhiyicx/xinshiji-iOS#17
- 【消息-聊天室】当消息内容为纯文字并且很长时，无法上滑查看全部内容 zhiyicx/xinshiji-iOS#19
- 【消息-联系人】键盘弹出之后把已选中的用户头像遮住 zhiyicx/xinshiji-iOS#20
- 【消息-聊天】普通成员仍然有群聊名称入口 zhiyicx/xinshiji-iOS#21
- 【消息-群聊】普通成员仍然可以邀请其他用户进入群聊 zhiyicx/xinshiji-iOS#24
- 【消息-聊天室】输入要发送的内容后断网点击“发送”没有反应 zhiyicx/xinshiji-iOS#25

**Comment by medz** [comment]
什么情况？

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年4月9日，11:56，mourui <notifications@github.com<mailto:notifications@github.com>> 写道：

ios
新增：

  *   【消息-群聊】有创建群信息时，在群聊天室没有显示 zhiyicx/xinshiji-iOS#2<https://github.com/zhiyicx/xinshiji-iOS/issues/2>
  *   【消息-群聊】已经有头像的在聊天室头像显示还是默认头像 zhiyicx/xinshiji-iOS#3<https://github.com/zhiyicx/xinshiji-iOS/issues/3>
  *   【消息-医生-在线咨询】非会员账号点击“在线咨询”进入的页面不对 zhiyicx/xinshiji-iOS#4<https://github.com/zhiyicx/xinshiji-iOS/issues/4>
  *   【消息-医生-在线咨询】会员账号点击“在线咨询”不能进入相应的页面 zhiyicx/xinshiji-iOS#6<https://github.com/zhiyicx/xinshiji-iOS/issues/6>
  *   【消息-聊天室】聊天室不显示emoji zhiyicx/xinshiji-iOS#7<https://github.com/zhiyicx/xinshiji-iOS/issues/7>
  *   【消息-聊天室】进入聊天信息页面点击头像进入其个人主页点击“关注”app崩溃 zhiyicx/xinshiji-iOS#10<https://github.com/zhiyicx/xinshiji-iOS/issues/10>
  *   【消息】在列表上滑动无法删除聊天室 zhiyicx/xinshiji-iOS#13<https://github.com/zhiyicx/xinshiji-iOS/issues/13>
  *   【消息-聊天室】发送图片在聊天室显示不对 zhiyicx/xinshiji-iOS#15<https://github.com/zhiyicx/xinshiji-iOS/issues/15>
  *   【消息】从聊天信息进入个人主页后返回消息列表会新增一个空白的聊天室区域 zhiyicx/xinshiji-iOS#17<https://github.com/zhiyicx/xinshiji-iOS/issues/17>
  *   【消息-聊天室】当消息内容为纯文字并且很长时，无法上滑查看全部内容 zhiyicx/xinshiji-iOS#19<https://github.com/zhiyicx/xinshiji-iOS/issues/19>
  *   【消息-联系人】键盘弹出之后把已选中的用户头像遮住 zhiyicx/xinshiji-iOS#20<https://github.com/zhiyicx/xinshiji-iOS/issues/20>
  *   【消息-聊天】普通成员仍然有群聊名称入口 zhiyicx/xinshiji-iOS#21<https://github.com/zhiyicx/xinshiji-iOS/issues/21>
  *   【消息-群聊】普通成员仍然可以邀请其他用户进入群聊 zhiyicx/xinshiji-iOS#24<https://github.com/zhiyicx/xinshiji-iOS/issues/24>
  *   【消息-聊天室】输入要发送的内容后断网点击“发送”没有反应 zhiyicx/xinshiji-iOS#25<https://github.com/zhiyicx/xinshiji-iOS/issues/25>

**Comment by maanrry** [comment]
发错了

**Comment by maanrry** [comment]
## Android
### 新增：
- 【发布】发布页面的排版与设计不符 zhiyicx/thinksns-plus-android#1922
- 【发布-短视频】录制视频完成后到上传封面点击“取消”app崩溃 zhiyicx/thinksns-plus-android#1923
- 【发布-视频】在编辑页面已经有一个视频之后选择重新录制进入的页面不对 zhiyicx/thinksns-plus-android#1924
- 【首页】列表上上下滑动短视频不是出于暂停状态 zhiyicx/thinksns-plus-android#1925
- 【发布-视频-录制页面】第一次关闭美颜时开关显示仍然是开着的 zhiyicx/thinksns-plus-android#1926
- 【发布-视频-编辑页面】缺少两个图标 zhiyicx/thinksns-plus-android#1927
- 【发布-视频-录制页面】正在录制的过程中点击“x”app崩溃 zhiyicx/thinksns-plus-android#1928
- 【发布-视频-录制页面】仍然显示了录制的时间 zhiyicx/thinksns-plus-android#1929
- 【发布-视频】发布编辑页面已存在一个视频后重新上传视频图标缺少名称 zhiyicx/thinksns-plus-android#1930
- 【发布-视频】录制过程中点击暂停之后再次进入录制页面是接着之前的视频录制 zhiyicx/thinksns-plus-android#1931
- 【发布-视频-录制页面】小于4秒仍然有“下一步” zhiyicx/thinksns-plus-android#1932
- 【发布-视频-视频编辑页面】添加滤镜样式与设计不符 zhiyicx/thinksns-plus-android#1933
- 【发布-视频】进入视频页面非常慢。建议优化 zhiyicx/thinksns-plus-android#1934
- 【首页】列表上和详情页的短视频title都有一个“tym” zhiyicx/thinksns-plus-android#1935
- 【首页-全屏播放短视频】播放完成后与设计不符 zhiyicx/thinksns-plus-android#1936
- 【首页】已经播放过的视频缺少本地缓存 zhiyicx/thinksns-plus-android#1937
- 【发布-视频-录制页面】点击“X”没有弹窗提示 zhiyicx/thinksns-plus-android#1938
- 【发布-视频】在发布页面点击返回提示不对  zhiyicx/thinksns-plus-android#1939
- 【发布-视频-视频编辑页面】点击"x"未进入视频录制页面 zhiyicx/thinksns-plus-android#1940
- 【首页】列表上短视频默认播放按钮位置不对 zhiyicx/thinksns-plus-android#1941
- 【首页】断网后播放视频没有提示检查网络 zhiyicx/thinksns-plus-android#1942
- 【首页】断网后播放视频没有提示检查网络 zhiyicx/thinksns-plus-android#1942
- 【首页】GIF全屏查看时仍然还是静态图  zhiyicx/thinksns-plus-android#1943
- 【首页】使用移动网络播放时弹窗提示内容没有显示全  zhiyicx/thinksns-plus-android#1944
- 【发布-视频】录制视频时反转了摄像头，再次进入录制页面时仍然使用是上一次的摄像头方向 zhiyicx/thinksns-plus-android#1945
- 【发布-视频】上传本地视频小于4秒，仍然可以进入裁剪页面 zhiyicx/thinksns-plus-android#1946
- 【首页】横屏录制的视频，在列表和详情展示错误 zhiyicx/thinksns-plus-android#1947
- 【首页-全屏播放】横屏录制的视频发布成功后全屏播放视频进度条仍然是竖着的 zhiyicx/thinksns-plus-android#1948
- 【发布-视频】小于4秒时录制了三段后不能继续录制 zhiyicx/thinksns-plus-android#1949
- 【发布-视频】未读出本地视频时进行录制完成后点击“下一步”app崩溃 zhiyicx/thinksns-plus-android#1950
- 【发布-视频】摄像头和语音权限被禁止之后，进入录制页面不对（机型适配） #1951

**Comment by LMTcancan** [comment]
## iOS
### 新增
- 【注册】邮箱注册各项输入正确，提示网络请求错误，实际注册成功 zhiyicx/thinksns-plus-ios#2086
- 【发布-视频】前置摄像头画面不是镜面显示 zhiyicx/thinksns-plus-ios#2087
- 【发布-视频】录制页面默认进入的是后置镜头，与用例不符 zhiyicx/thinksns-plus-ios#2088
- 【首页-最新】在wifi环境下会自动播放列表中的视频，与需求不符 zhiyicx/thinksns-plus-ios#2089
- 【发布】发布页面与设计图不符 zhiyicx/thinksns-plus-ios#2090
- 【发布-视频】录制页面没有美颜效果，关闭美颜图标与设计不符 #2091
- 【发布-视频】录制页面亮度较暗，前置摄像头比较明显 zhiyicx/thinksns-plus-ios#2092
- 【发布-视频】分段录制过程中，页面与设计图不符 zhiyicx/thinksns-plus-ios#2093
- 【发布-视频】录制超过10秒后，自动进入编辑视频，页面显示灰色 zhiyicx/thinksns-plus-ios#2094
- 【发布-视频-视频编辑】5S上编辑的title与状态栏重叠 zhiyicx/thinksns-plus-ios#2095
- 【发布-视频】录制过程中无法点击聚焦，与用例不符 zhiyicx/thinksns-plus-ios#2096
- 【发布-视频】取消录制时缺少弹框，与用例不符 zhiyicx/thinksns-plus-ios#2097
- 【发布-视频】录制页面，分段删除视频时缺少提示 zhiyicx/thinksns-plus-ios#2098
- 【发布-视频】发布的视频成功上传到服务器前，能够点赞和点击更多，与用例不符 zhiyicx/thinksns-plus-ios#2099
- 【首页】自己发布的视频，点击更多，缺少删除和申请置顶，多了举报 zhiyicx/thinksns-plus-ios#2100
- 【发布-视频】在发布页面选择重新录制，选择录制后不能进入录制页面 zhiyicx/thinksns-plus-ios#2101
- 【发布-视频】录制完成或选择好的本地视频，点击预览的时候没有全屏显示 zhiyicx/thinksns-plus-ios#2102
- 【发布-视频】编辑视频页面点击取消按钮无反应， title错误 zhiyicx/thinksns-plus-ios#2103
- 【发布-视频】视频预览页面，点击删除后，没有删除视频 zhiyicx/thinksns-plus-ios#2104
- 【发布-视频】放弃发布视频时，缺少保存草稿箱提示 zhiyicx/thinksns-plus-ios#2105
- 【首页-动态详情】有人点赞时，点赞头像多显示了一个，刷新后头像又增加 zhiyicx/thinksns-plus-ios#2106
- 【首页】非WIFI下播放视频，提示框与设计图不符 zhiyicx/thinksns-plus-ios#2107
- 【首页】在列表页播放视频点击全屏，按左上角返回后，全屏按钮图标显示有误 zhiyicx/thinksns-plus-ios#2108
- 【全局】全屏播放视频时不应该显示状态栏 zhiyicx/thinksns-plus-ios#2109
- 【首页】在列表页点击全屏播放横屏的视频，没有横屏全屏 zhiyicx/thinksns-plus-ios#2110
- 【首页-动态详情】竖屏的视频点击全屏时，会横屏显示 zhiyicx/thinksns-plus-ios#2111
- 【全局】全屏播放完后，显示与设计图不符 zhiyicx/thinksns-plus-ios#2112
- 【首页】断开网络后点击视频，提示错误 zhiyicx/thinksns-plus-ios#2114
- 【全局】播放视频时，由WiFi切换到移动网络，没有暂停视频并提示 zhiyicx/thinksns-plus-ios#2115
- 【全局】在移动网络下，已经确认使用移动网络播放，再点击其他视频还会提示，与用例不符 zhiyicx/thinksns-plus-ios#2116
- 【首页】在列表播放视频点击全屏，返回后状态栏消失 zhiyicx/thinksns-plus-ios#2117
- 【全局】正在播放的视频被第三方打断后，返回APP，视频没有处于暂停状态 zhiyicx/thinksns-plus-ios#2118
- 【首页-动态详情】WiFi下进入动态详情会自动播放视频，与用例不符 zhiyicx/thinksns-plus-ios#2119
- 【首页-动态详情】进入他人的动态详情，点击更多，缺少举报 zhiyicx/thinksns-plus-ios#2120
- 【全局】点击自己的评论没有弹窗，而是直接回复 zhiyicx/thinksns-plus-ios#2121
- 【发布-视频】选择时间少于4秒的本地视频能够发布成功 zhiyicx/thinksns-plus-ios#2122
- 【全局】播放视频时，双击视频暂停，再次双击视频继续播放 zhiyicx/thinksns-plus-ios#2123
- 【发布-视频】分段录制时，在录制过程中点击删除上一个分段录制，进度条没有退回到上一个录制开始前 zhiyicx/thinksns-plus-ios#2124
