### ISSUE TITLE
2018-04-11 9.00AM-12.00AM | 阿门 - e港e店 | 需求测试

### ISSUE THREAD

**Issue by medz** [zhiyicx/test-group-worker-forum#106]
2018-04-11 9.00AM-12.00AM | 阿门 - e港e店 | 需求测试

## 基本信息

- 测试项目：阿门 - e港e店
- 测试版本：v1.0.0
- 对接人：龚金海
- 需求时间：2018-04-11 9.00AM-12.00AM
- 需求人数：2 人

## 仓库

| 仓库名称 | 仓库地址 |
|:----:|----|
| 项目 | https://github.com/zhiyicx/jipu-amen |

## 目的

- [x] 交付需求测试

## 测试内容

- [ ] 阿门e港e店升级第一轮测试

## 模板

```
zhiyicx/jipu-amen#100
```

> 将上述的 100 替换为对应的 Issue 编号

**Comment by maanrry** [comment]
### 新增：
- 【首页】光标移动到首页仍然显示了一级菜单 zhiyicx/jipu-amen#10
- 【首页】二级导航重复显示一级导航 zhiyicx/jipu-amen#11
- 【首页】多处尺寸不对 zhiyicx/jipu-amen#13
- 【后台-买手团】没有添加买手描述时，提示买手小头像不能为空 zhiyicx/jipu-amen#15
- 【后台-买手团-新增】将已上传的买手图片删除之后就不能再上传了 zhiyicx/jipu-amen#17
- 【首页-体验店】向左滑动与设计不符 zhiyicx/jipu-amen#24
- 【H5-买手团】页面混乱，与设计不符 zhiyicx/jipu-amen#25
- 【H5-首页】买手团与设计不符 zhiyicx/jipu-amen#26
- 【H5-首页】立即购买与商品价格重叠 zhiyicx/jipu-amen#27
- 【H5-首页】“品牌馆”名字不对 zhiyicx/jipu-amen#28
- 【H5-首页--线下体验店】缺少“more” zhiyicx/jipu-amen#29
- 【H5-线下体验店】左右两边没有间距 zhiyicx/jipu-amen#30
- 【H5-线下体验店】当简介为纯英文时导致页面排版混乱 zhiyicx/jipu-amen#31
- 【线下体验店】当简介为纯英文时导致页面排版混乱 zhiyicx/jipu-amen#32
- 【H5-线下体验店】地图点击之后未打开百度地图 zhiyicx/jipu-amen#33
- 【后台-线下体验店】仅修改商店名称时提示不对 zhiyicx/jipu-amen#34
- 【H5-线下体验店】缺少标题 zhiyicx/jipu-amen#35
- 【H5-买手详情页】点击商品信息之后相关的商品信息就消失了 zhiyicx/jipu-amen#36
- 【H5-买手详情】超过12个商品仍然显示出来了 zhiyicx/jipu-amen#37
- 【首页-二级导航栏】二级导航栏的字数色号不对 zhiyicx/jipu-amen#38
- 【后台-买手管理-线下体验店】新增时仅上传体验店大图时一直提示大图不能为空 zhiyicx/jipu-amen#39
- 【后台-订单导出】一个订单都没有勾选时仍然可以导出订单 zhiyicx/jipu-amen#40

**Comment by LMTcancan** [comment]
## PC
### 已修复
- 【后台-商品管理-下架】选择多个商品下架时，确认操作后商品没有下架，且下架按钮无法点击 zhiyicx/jipu-amen#3
- 【后台-商品管理-编辑商品】添加好的商品进行重新编辑时，商品分类只剩第一大类 zhiyicx/jipu-amen#4
- 【后台-商品管理】商品列表中点击某一商品品名，会进入新增商品页面 zhiyicx/jipu-amen#5
- 【商品列表-商品详情】商品文字简介与设计图不符 zhiyicx/jipu-amen#7
- 【后台-商品管理-商品列表】点击按售价/库存排序时，页面崩溃 zhiyicx/jipu-amen#8
- 【后台-商品管理-新增商品】缺少购物须知 zhiyicx/jipu-amen#9


### 重新打开
- 【商品列表】商品列表多处与设计图不符 zhiyicx/jipu-amen#2

### 新增
- 【后台-买手团-买手列表-编辑买手】买手简介字数没有做限制 zhiyicx/jipu-amen#12
- 【后台-买手团-买手列表-编辑买手】买手描述不是图文编辑器，应该是直接上传图片 zhiyicx/jipu-amen#14
- 【买手团详情】详情页尺寸有多处不正确 zhiyicx/jipu-amen#16
- 【买手团详情】商品信息字体颜色与设计图不符 zhiyicx/jipu-amen#18
- 【买手团详情】点击“MORE”按钮，除了买手推荐分类为化妆品的跳转正确，其他都会出错 zhiyicx/jipu-amen#19
- 【后台-买手团-买手推荐商品列表】不需要填写“排序”，与需求不符 zhiyicx/jipu-amen#20
- 【后台-买手团-线下体验店】体验店名称字数超过20字后，提示错误 zhiyicx/jipu-amen#21
- 【线下体验店详情】地图尺寸不对 zhiyicx/jipu-amen#22
- 【线下体验店详情】地图上不能打点，与需求不符 zhiyicx/jipu-amen#23
