### ISSUE TITLE
2018-04-11 1.30.00PM-6.00PM | ThinkSNS Plus - PC | 修复测试

### ISSUE THREAD

**Issue by medz** [zhiyicx/test-group-worker-forum#107]
2018-04-11 1.30.00PM-6.00PM | ThinkSNS Plus - PC | 修复测试

## 基本信息

- 测试项目：ThinkSNS Plus
    - PC 端
- 测试版本：*
- 对接人：贺泽都
- 需求时间：2018-04-11 1.30.00PM-6.00PM
- 需求人数：2 人

## 仓库

| 仓库名称 | 仓库地址 |
|:----:|----|
| 项目 | https://github.com/zhiyicx/plus-component-pc |

## 目的

- [x] 交付需求测试

## 测试内容

- 针对仓库上标记 `Fixed` 的 Issues 进行复测

## 模板

```
zhiyicx/plus-component-pc#100
```

> 将上述的 100 替换为对应的 Issue 编号

**Comment by maanrry** [comment]
## pc端：
### 已修复：
- 【设置】三方注册的账号去绑定手机是提示不对 zhiyicx/plus-component-pc#479
- 【登录】已注册成功的第三方账号授权之后未进入动态 zhiyicx/plus-component-pc#768
- 【排行榜】列表上的图标和个人中心的图标不一致 zhiyicx/plus-component-pc#767
- 【问答】问答达人排行点击头像未进入其个人主页 zhiyicx/plus-component-pc#765
- 【消息】当内容过长时无论在评论的/点赞的列表上显示错误 zhiyicx/plus-component-pc#764
- 【问答-话题详情】缺少专家列表 zhiyicx/plus-component-pc#763
- 【注册】邮箱注册报错 zhiyicx/plus-component-pc#747

**Comment by LMTcancan** [comment]
## PC
### 已修复
- 【个人主页--收藏】回答收藏一直处于加载中 zhiyicx/plus-component-pc#369
- 【我的积分】后台关闭充值提现开关后，我的积分页面样式错误 zhiyicx/plus-component-pc#680
- 【我的钱包】钱包未使用新的接口，导致数据与APP不一样 zhiyicx/plus-component-pc#693
- 【动态详情】动态详情页缺少举报 zhiyicx/plus-component-pc#697
- 【个人主页-圈子】圈子显示内容与设计图不符 zhiyicx/plus-component-pc#719
- 【全局】设置收费或申请置顶时，金额填写为非整数，提示语不对 zhiyicx/plus-component-pc#740
- 【问答-话题】下滑加载更多话题时排版出现错误 zhiyicx/plus-component-pc#741
- 【问答-回答详情】未围观的回答进入回答详情没有显示回答内容 zhiyicx/plus-component-pc#742
- 【问答-话题】话题详情页点击“分享”话题的图标分享三方弹窗会闪 zhiyicx/plus-component-pc#744
- 【个人中心-问答】问答页面出现认证图标 zhiyicx/plus-component-pc#746
- 【全局】打赏成功后钱包余额未减少 zhiyicx/plus-component-pc#748
- 【他人的个人主页】积分数据不对 zhiyicx/plus-component-pc#750
- 【聊天】点击“+”提示出错了 zhiyicx/plus-component-pc#753
- 【个人主页】已认证用户缺少认证描述，与设计图不符 zhiyicx/plus-component-pc#754
- 【他人个人主页】缺少他人粉丝和关注列表，与设计图不符 zhiyicx/plus-component-pc#755
- 【全局打赏】打赏用户昵称很长时排版太丑 zhiyicx/plus-component-pc#756
- 【问答-回答详情】回答打赏弹窗不对 zhiyicx/plus-component-pc#758
- 【圈子-圈子详情】右侧边热门圈子当圈子名称很长时未用“.......” zhiyicx/plus-component-pc#759
- 【动态-动态详情】游客模式可以查看动态详情，与用例不符 zhiyicx/plus-component-pc#760
- 【个人主页】未认证时点击“投稿”未弹出“去认证” zhiyicx/plus-component-pc#761
- 【动态】发布图片动态时，点击图片无反应 zhiyicx/plus-component-pc#769


### 重新打开
- 【聊天室】能发送空消息 zhiyicx/plus-component-pc#465
- 【我的钱包】充值积分用钱包余额充值后，钱包余额没扣除 zhiyicx/plus-component-pc#692
- 【我的钱包-提现】提现成功后，在交易明细中未显示，实际钱包余额有被扣除 zhiyicx/plus-component-pc#714
- 【问答-问题详情】邀请用户的昵称很长时，页面排版与设计不符 zhiyicx/plus-component-pc#724
- 【全局-详情页】详情页的打赏头像与打赏列表的头像不一致 zhiyicx/plus-component-pc#734
- 【个人中心-圈子】帖子列表缺少“申请置顶”入口 zhiyicx/plus-component-pc#745
- 【找伙伴-推荐】推荐的好友只显示了后台推荐的用户 zhiyicx/plus-component-pc#752
- 【问答-问答详情】鼠标移到问答的关注人数不应该有变化效果 zhiyicx/plus-component-pc#766

### 新增
- 【动态】发布图片动态时，点击图片无反应 zhiyicx/plus-component-pc#769
- 【圈子-圈子详情】右侧热门圈子排名数字显示不正确 zhiyicx/plus-component-pc#770
- 【设置】新注册的第三方账号，去绑定手机和邮箱事没有提示先去设置密码 zhiyicx/plus-component-pc#771
- 【他人个人主页-圈子】他的圈子列表显示为我的圈子列表 zhiyicx/plus-component-pc#772
- 【个人主页-收藏-回答】收藏的付费回答，未付费时，点击无反应 zhiyicx/plus-component-pc#773
- 【个人主页-收藏-回答】在收藏列表评论回答时，点击申请置顶无反应 zhiyicx/plus-component-pc#774
- 【通知】选择聊天、评论的、点赞的，用户头像一些是圆形一些是方形 zhiyicx/plus-component-pc#775
- 【聊天】选择联系人搜索，搜索结果显示为全部联系人 zhiyicx/plus-component-pc#776
- 【我的钱包-交易明细】交易明细显示金额与实际金额不符 zhiyicx/plus-component-pc#777
- 【圈子-圈子详情-圈子成员】成员头像缺少认证图标 zhiyicx/plus-component-pc#778
