### ISSUE TITLE
2018-04-12 9.00AM-6.00PM | 轰米社区 | 客户端复测

### ISSUE THREAD

**Issue by medz** [zhiyicx/test-group-worker-forum#108]
## 基本信息

- 测试项目：轰米社区
    - iOS 端
    - Android 端
- 测试版本：v1.0.6
- 对接人：李育东
- 测试时间：2018-04-12 9.00AM-6.00PM
- 需求人数：2人

## 仓库

| 仓库名称 | 仓库地址 |
|----|----|
| iOS 仓库 | https://github.com/zhiyicx/t4-homie-ios |
| Android 仓库 | https://github.com/zhiyicx/t4-homie-android |

## 测试目的

- [x] 交付客户测试

## 测试内容

- [ ] iOS，Android复测

**Comment by maanrry** [comment]
## Android：
###新增：
-【新鲜事】允许访问当前位置转发他人的新鲜事后在新鲜事列表上没显示地址 zhiyicx/t4-homie-android#221
- 【homie-消息-互动】点击新鲜事内容的话题进入话题详情页后，返回互动列表内容被遮挡 zhiyicx/t4-homie-android#222
- 【homie-发现-活动】发布活动各项输入完成之后无法发布成功 zhiyicx/t4-homie-android#226
- 【homie-发现-活动】活动列表上时间的样式与设计不符 zhiyicx/t4-homie-android#230
- 【homie-发现-靠谱榜】列表上靠谱指数多了“：”与设计不符 zhiyicx/t4-homie-android#233
- 【我的-认证】认证被驳回之后将认证附件删除之后占位图不是默认的图片 zhiyicx/t4-homie-android#235
- 【我的-更多-我的收藏】列表上有两个取消按钮 zhiyicx/t4-homie-android#237
- 【我的-更多-我的收藏】在列表上回复他人的评论时没有弹出输入框 zhiyicx/t4-homie-android#238
- 【我的-更多-草稿箱】“清空”按钮不是主题色 zhiyicx/t4-homie-android#240


## ios
### 新增：
- 【新鲜事】新注册的账号关注/同校栏目下出现null数据 zhiyicx/t4-homie-ios#254
- 【我的-资料-学校】进入学校编辑页面学校名称没有展示全 zhiyicx/t4-homie-ios#255
- 【homie-消息-互动】新鲜事内容含话题时在互动列表上蓝色显示，期望没有特殊的颜色标识 zhiyicx/t4-homie-ios#257
- 【homie-发现-活动】活动评论列表用户昵称没有显示全 zhiyicx/t4-homie-ios#260
- 【homie-发现-活动】参与活动人数列表交集数的样式与设计不符 zhiyicx/t4-homie-ios#261
- 【homie-发现-靠谱榜】排序不对 zhiyicx/t4-homie-ios#265
- 【我的-成就认证】发布了成就认证并且有人点赞之后没有进度条 zhiyicx/t4-homie-ios#270
- 【我的-更多-意见反馈】发送的意见反馈含图片时发送成功之后未恢复成初始状态 zhiyicx/t4-homie-ios#272
- 【我的-更多-设置-黑名单】缺少靠谱指数 zhiyicx/t4-homie-ios#273
- 【我的-更多-设置-关于我们】背景颜色仍然还是白色 zhiyicx/t4-homie-ios#274

**Comment by LMTcancan** [comment]
## iOS 
### 已修复
- 【我的-生涯-日迹】列表上没有显示评论数和点赞数 zhiyicx/t4-homie-ios#246
- 【他人个人主页-生涯-日迹】查看他人日迹时，滑动到固定位置界面卡死（特殊账号） zhiyicx/t4-homie-ios#238
- 【发布新鲜事】先录制视频然后再拍照上传，将图片删除之后还是视频图标 zhiyicx/t4-homie-ios#236
- 【HOMIE-发现-活动-活动评论】点击头像进入的是T4的个人主页 zhiyicx/t4-homie-ios#233
- 【homie-消息】先将聊天室删除后有陌生人发送消息后最后一次被删除的聊天室会出现在列表上 zhiyicx/t4-homie-ios#232
- 【我的-生涯-日迹】转发的新鲜事展示有多处错误 zhiyicx/t4-homie-ios#231
- 【登录】当输入的手机号错误时，修改除了最后一位的任意一位或几位并且满足11位时不再出现“获取验证码” zhiyicx/t4-homie-ios#229
- 【我的-更多-意见反馈】图片上传后变形 zhiyicx/t4-homie-ios#223
- 【新鲜事-话题-话题详情】在列表上点击“更多”没有反应 zhiyicx/t4-homie-ios#194
- 【homie--活动--活动详情】缺少发布活动的用户头像 zhiyicx/t4-homie-ios#170
- 【新鲜事】当用户为关注任何人时，关注页面缺少缺省图 zhiyicx/t4-homie-ios#137
- 【新鲜事-发布】第一次发布视频时，提示框与整体效果不符 zhiyicx/t4-homie-ios#228
- 【HOMIE-发现-活动】报名活动后，“审核中”按钮仍然可以点击进行报名 zhiyicx/t4-homie-ios#119
- 【登录】ios端184开头的手机号登录时输入正确的手机号没有出现“获取验证码” zhiyicx/t4-homie-ios#248


### 重新打开
- 【我的-更多-意见反馈】意见反馈添加图片数量未做限制，与需求不符 zhiyicx/t4-homie-ios#243
- 【HOMIE-消息-互动】活动评论内容过多时，未做适配，会发生遮挡 zhiyicx/t4-homie-ios#235
- 【新鲜事】新鲜事带有话题和@时，转发后话题颜色没有变蓝，@显示错误 zhiyicx/t4-homie-ios#230

### 新增
- 【HOMIE-消息-互动】无法上拉加载更多内容 zhiyicx/t4-homie-ios#247
- 【登录】ios端184开头的手机号登录时输入正确的手机号没有出现“获取验证码” zhiyicx/t4-homie-ios#248
- 【HOMIE-消息-互动】点击别人点赞的内容会进入他人个人主页 zhiyicx/t4-homie-ios#249
- 【新鲜事-话题-搜索】搜索结果不需要显示“热门话题”和“正在发生中的话题” zhiyicx/t4-homie-ios#250
- 【HOMIE-消息-聊天室信息】修改群名称时，页面与整体风格不一致 zhiyicx/t4-homie-ios#251
- 【HOMIE-消息-聊天室】聊天室有几处与设计图不符 zhiyicx/t4-homie-ios#252
- 【新鲜事】未关注用户匿名发布新鲜事时，有关注按钮 zhiyicx/t4-homie-ios#253
- 【新鲜事】评论新鲜事时，发布评论成功后没有显示出评论，需要刷新后才显示 zhiyicx/t4-homie-ios#256
- 【全局】所有人的认证图标都没有 zhiyicx/t4-homie-ios#258
- 【新鲜事-发布】录制视频，取消时，弹窗与整体风格不一致 zhiyicx/t4-homie-ios#259
- 【新鲜事-发布】视频录制页面多处UI不对 zhiyicx/t4-homie-ios#262
- 【他人个人主页】已关注的用户取消关注按钮显示与设计图不符 zhiyicx/t4-homie-ios#263
- 【新鲜事】在新鲜事列表点击关注时，只有点击的那一个关注按钮消失，同一个人发布的其他新鲜事的关注按钮未消失 zhiyicx/t4-homie-ios#264
- 【新鲜事-发布】发布页面多出与设计图不符 zhiyicx/t4-homie-ios#266
- 【新鲜事】他人转发的新鲜事，点击头像无法进入他人个人主页 zhiyicx/t4-homie-ios#267
- 【他人个人主页-生涯-日迹】给某一个新鲜事点赞时，点赞数没有增加 zhiyicx/t4-homie-ios#269
- 【新鲜事-新鲜事详情】点赞列表中，自己点赞的不需要交集数 zhiyicx/t4-homie-io#271


## Android
### 已修复
- 【HOMIE-发现-活动-活动评论】输入评论内容后断开网络，点击评论，提示错误 zhiyicx/t4-homie-android#201
- 【新鲜事-话题-搜索】搜索结果展示错误 zhiyicx/t4-homie-android#202
- 【HOMIE-发现】当可能认识的人没有时，占位文字显示错误 zhiyicx/t4-homie-android#205
- 【我的-更多-相册】选择多张图片上传时，只上传成功一张图片 zhiyicx/t4-homie-android#206
- 【我的-更多-相册】当相册没有图片时，上传图片，缺省图未消失 zhiyicx/t4-homie-android#208
- 【HOMIE-消息-陌生人】在消息页面多次点击进入群聊后退出，进入陌生人消息会出现其他聊天信息 zhiyicx/t4-homie-android#199


### 重新打开
- 【HOMIE-消息-互动】互动列表全部显示为默认头像 zhiyicx/t4-homie-android#197
- 【HOMIE-消息-互动】互动消息有多处错误 zhiyicx/t4-homie-android#200
- 【新鲜事-话题-话题详情】有两处与设计图不符 zhiyicx/t4-homie-android#204
- 【我的-更多-相册】编辑相册，缺少删除按钮，点击删除多张图片，APP崩溃 zhiyicx/t4-homie-android#207

### 新增
- 【我的-更多-意见反馈】添加图片之后点击发送，提示上传失败 zhiyicx/t4-homie-android#209
- 【HOMIE-消息-陌生人】有多个陌生人来信时，刷新会导致头像错乱 zhiyicx/t4-homie-android#210
- 【HOMIE-消息-互动】点击用户头像没有进入他人个人主页 zhiyicx/t4-homie-android#211
- 【HOMIE-消息-聊天室】退出群聊后，聊天室没有消失，再次点击能够进入聊天室并且发送消息 zhiyicx/t4-homie-android#213
- 【HOMIE-消息-聊天室】修改了昵称后，在群聊中还是显示为之前的昵称 zhiyicx/t4-homie-android#214
- 【HOMIE-消息-聊天室信息】查看群聊信息修改群聊头像时，选择图片后修建图片样式与整体风格不一致 zhiyicx/t4-homie-android#215
- 【HOMIE-消息-聊天室】群名称被修改太长时，显示与返回按钮和更多按钮有遮挡 zhiyicx/t4-homie-android#216
- 【新鲜事-新鲜事详情】点赞和评论数量显示与设计图不符 zhiyicx/t4-homie-android#217
- 【新鲜事】未关注用户匿名发布新鲜事时，有关注按钮 zhiyicx/t4-homie-android#218
- 【新鲜事-话题】进入更多话题列表，APP崩溃 zhiyicx/t4-homie-android#219
- 【新鲜事-新鲜事详情】删除自己评论的内容后刷新，评论总数没有变 zhiyicx/t4-homie-android#220
- 【新鲜事】在新鲜事列表评论，缺少emoji按钮 zhiyicx/t4-homie-android#223
- 【新鲜事】新鲜事评论较多时，在列表中显示评论数错误 zhiyicx/t4-homie-android#224
- 【HOMIE-消息】下拉刷新后，刷新提示未消失，遮挡“互动” zhiyicx/t4-homie-android#225
- 【新鲜事-发布】录制视频，取消时，弹窗与整体风格不一致 zhiyicx/t4-homie-android#227
- 【新鲜事】举报不输入内容仍然可以举报成功 zhiyicx/t4-homie-android#228
- 【我的-更多-我的收藏】收藏的新鲜事有多条评论时，样式与设计图不符 zhiyicx/t4-homie-android#229
- 【HOMIE-发现-活动详情】点击活动封面不能查看大图 zhiyicx/t4-homie-android#231
- 【新鲜事】刷新新鲜事列表，会出现错误界面 zhiyicx/t4-homie-android#232
- 【新鲜事-话题-话题详情】进入未关注人的话题详情点击关注，返回后在列表中关注按钮还存在 zhiyicx/t4-homie-android#234
- 【新鲜事】点赞数超过5个后，在列表也显示数量为5个 zhiyicx/t4-homie-android#236
- 【新鲜事-发布】选择HOMIE可见后，在发布页显示错误 zhiyicx/t4-homie-android#239
- 【新鲜事】他人转发的新鲜事，没有显示备注 zhiyicx/t4-homie-android#241
- 【他人个人主页】在个人主页拉黑某人后，再次点击更多按钮，弹框提示还是“拉黑” zhiyicx/t4-homie-android#242

**Comment by maanrry** [comment]
[轰米bug-0329 iOS、Android0412复测.xlsx](https://github.com/zhiyicx/test-group-worker-forum/files/1902672/bug-0329.iOS.Android0412.xlsx)
[Uploading Homie(1.0.2)测试报告_MTC_Android 2.xlsx…]()
