### ISSUE TITLE
2018-04-13 9.00AM-12.00AM | 阿门 e港 e店 | 交付客户测试

### ISSUE THREAD

**Issue by medz** [zhiyicx/test-group-worker-forum#109]
2018-04-11 9.00AM-12.00AM | 阿门 - e港e店 | 需求测试

## 基本信息

- 测试项目：阿门 - e港e店
- 测试版本：v1.0.0
- 对接人：龚金海
- 需求时间：2018-04-11 9.00AM-12.00AM
- 需求人数：2 人

## 仓库

| 仓库名称 | 仓库地址 |
|:----:|----|
| 项目 | https://github.com/zhiyicx/jipu-amen |

## 目的

- [x] 交付需求测试

## 测试内容

- [ ] 阿门e港e店升级第一轮测试

## 模板

```
zhiyicx/jipu-amen#100
```

> 将上述的 100 替换为对应的 Issue 编号

**Comment by maanrry** [comment]
### 已修复：
- 【后台-买手管理-线下体验店】新增时仅上传体验店大图时一直提示大图不能为空 zhiyicx/jipu-amen#39
- 【首页-二级导航栏】二级导航栏的字数色号不对 zhiyicx/jipu-amen#38
- 【H5-买手详情】超过12个商品仍然显示出来了 zhiyicx/jipu-amen#37
- 【H5-买手详情页】点击商品信息之后相关的商品信息就消失了 zhiyicx/jipu-amen#36
- 【后台-线下体验店】仅修改商店名称时提示不对 zhiyicx/jipu-amen#34
- 【线下体验店】当简介为纯英文时导致页面排版混乱 zhiyicx/jipu-amen#32
- 【H5-线下体验店】左右两边没有间距 zhiyicx/jipu-amen#30
- 【H5-首页】买手团与设计不符 zhiyicx/jipu-amen#26
### 新增：
 - 【首页】光标聚焦到“首页”未出现二级菜单栏 zhiyicx/jipu-amen#41
- 【H5-首页-品牌馆】“more”的样式右边框没有了 zhiyicx/jipu-amen#42
- 【H5-首页】顶部的搜索占位文字的位置与设计不符 zhiyicx/jipu-amen#43
- 【H5-首页】推荐商品一与推荐商品二之间的广告尺寸与设计不符 zhiyicx/jipu-amen#44
- 【H5-首页-体验店】体验店名称很长时未用省略号表示 zhiyicx/jipu-amen#47
- 【首页】“more”的样式与设计不符 zhiyicx/jipu-amen#49
- 【首页-线下体验店】连续多次左右翻滚页面卡死 zhiyicx/jipu-amen#51

**Comment by LMTcancan** [comment]
### 重新打开
- 【买手团详情】点击“MORE”按钮，除了买手推荐分类为化妆品的跳转正确，其他都会出错 zhiyicx/jipu-amen#19
- 【后台-买手团-线下体验店】体验店名称字数超过20字后，提示错误 zhiyicx/jipu-amen#21


### 新增
- 【我的购物车】商品信息展示有误，缺少商品单选框 zhiyicx/jipu-amen#45
- 【订单支付】没有默认选择支付宝，点击“去支付”会默认进入支付宝支付页面 zhiyicx/jipu-amen#46
- 【商品列表】在“国家”选择多选后，最后一个国家图标会被遮挡 zhiyicx/jipu-amen#48
- 【H5-买手团详情】买手团详情多处问题 zhiyicx/jipu-amen#50
- 【H5-买手团详情】点击“MORE”，所有都会进入到化妆品类别的商品列表页 zhiyicx/jipu-amen#52
- 【H5-体验店详情】体验店标题较长时，在地图显示会与图标有遮挡 zhiyicx/jipu-amen#53
